spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "lty_2011"

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin